sudo: false
language: python
python:
  - "2.7"
notifications:
  slack: ooi-dev:e6WpBt9NHHw1YJjRKuYHkhYr

# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda

# Install packages
install:
  - conda create --yes -n preload python=2.7 pandas nose sqlalchemy
  - source activate preload
  - pip install numpy==1.12.0
  - conda install --yes -c conda-forge -c ooi ion-functions=2.4.3
  - pip install -r requirements.txt
  - pip install git+https://github.com/oceanobservatories/ooi-data@v0.0.5

before_script:
  - "rm __init__.py"

# command to run tests
script:
  - nosetests

